name: WiFiSign
author: hasashin
version: 1.1
description: This plugin is able to send redstone through air.
main: pl.poznan.put.WiFiSign
api-version: 1.14

softdepend: [Vault]

commands:

#TODO: Update Permissions!
permissions:
  WiFi.*:
    description: Gives you all permissions.
    default: true