name: WiFiSign
author: hasashin
version: 1.2
description: This plugin is able to send redstone through air.
main: pl.poznan.put.WiFiSign
api-version: 1.14

softdepend: [Vault]

commands:
  wifireload:
    description: Reloads all signs
    usage: /wifireload 
    permission: WiFi.reload

#TODO: Update Permissions!
permissions:
  WiFi.*:
    description: Gives you all permissions.
    default: true
  WiFi.reload:
    default: true