name: WiFiSign
author: hasashin
version: 1.3
description: This plugin is able to send redstone through air.
main: pl.poznan.put.WiFiSign
api-version: 1.14

softdepend: [Vault]

commands:
  wifireload:
    description: Reloads all signs
    usage: /wifireload 
    permission: WiFi.reload
  wifinets:
    description: Gets list of existing networks
    usage: /wifinets
    permission: WiFi.list

#TODO: Update Permissions!
permissions:
  WiFi.*:
    description: Gives you all permissions.
    default: op
  WiFi.reload:
    default: op
  WiFi.list:
    default: op